import os
import time
import requests
import json

# =====================================================================
# ⚙️ 設定：強烈建議使用 gemma2, qwen2.5 或 llama3-taiwan，中文跟 JSON 才會穩
# =====================================================================
MODEL_NAME = "llama3:latest" 
OLLAMA_URL = "http://localhost:11434/api/chat" # 換成 chat API 才能記錄對話歷史

def clear_screen():
    os.system('cls' if os.name == 'nt' else 'clear')

def slow_print(text, delay=0.01):
    for char in text:
        print(char, end='', flush=True)
        time.sleep(delay)
    print()

def ask_ai_game_master(messages):
    """呼叫 Ollama，並強迫其回傳 JSON 格式"""
    try:
        payload = {
            "model": MODEL_NAME,
            "messages": messages,
            "stream": False,
            "format": "json" # 強迫 Ollama 回傳 JSON 格式
        }
        response = requests.post(OLLAMA_URL, json=payload, timeout=30)
        if response.status_code == 200:
            # 解析 AI 回傳的 JSON 字串
            content = response.json().get("message", {}).get("content", "")
            return json.loads(content)
        else:
            print(f"\n❌ AI 伺服器異常，狀態碼: {response.status_code}")
            return None
    except Exception as e:
        print(f"\n❌ 連線失敗或 JSON 解析錯誤: {e}")
        return None

def main_game():
    clear_screen()
    print("=========================================================")
    print(" 🤖 Fully AI-Driven Dungeon: World Generated by AI v1.0 ")
    print("=========================================================")
    player_name = input("\nPlease enter your engineer codename: ").strip()
    if not player_name: player_name = "Noob_Engineer"

    # 1. 初始化 System Prompt：拿掉所有中文限制，改用全英文規範
    system_prompt = (
        f"You are a witty, sarcastic Game Master (GM) full of insider tech and programming jokes.\n"
        f"The player's name is '{player_name}', and they are trying to escape a tech building locked down by a rogue AI.\n"
        f"You must drive the story development, random events, and the final ending. You decide whether the player survives or dies.\n\n"
        f"CRITICAL! Your response MUST strictly follow this JSON format, with no other conversational text outside the JSON:\n"
        f"{{\n"
        f"  \"story\": \"Describe the current plot (within 150 words, full of tech humor)\",\n"
        f"  \"option_1\": \"Action plan for option 1\",\n"
        f"  \"option_2\": \"Action plan for option 2\",\n"
        f"  \"game_over\": false (set to true if the player wins, escapes, or dies; otherwise false),\n"
        f"  \"ending_status\": \"Set to 'SUCCESS' if they escape, 'FAIL' if they die; otherwise keep it empty ''\"\n"
        f"}}"
    )

    # 2. 建立對話歷史紀錄
    game_history = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": "Game start! Please generate the opening chapter and the two initial options."}
    ]

    round_count = 1
    while True:
        clear_screen()
        print(f"⏳ 【Current Round: {round_count}】")
        print("─" * 55)
        print("🤖 AI is weaving the timeline (English Mode)...")
        
        # 呼叫 AI (建議保留之前的 timeout=60 比較保險)
        ai_response = ask_ai_game_master(game_history)
        
        if not ai_response:
            print("Failed to get valid JSON from AI. Game terminated.")
            break

        # 將 AI 的回應加進對話歷史
        game_history.append({"role": "assistant", "content": json.dumps(ai_response)})

        # 顯示劇情
        clear_screen()
        print(f"⏳ 【Round {round_count}】")
        print("─" * 55)
        slow_print(ai_response.get("story", "No story generated."))
        print("─" * 55)

        # 檢查遊戲是否結束
        if ai_response.get("game_over", False) or ai_response.get("ending_status") in ["SUCCESS", "FAIL"]:
            status = ai_response.get("ending_status", "FAIL")
            if status == "SUCCESS":
                print("\n🎉 【CONGRATULATIONS】You successfully escaped the building! The rogue AI spared your life!")
            else:
                print("\n💀 【GAME OVER】You died. Your soul is now a background process in the server.")
            break

        # 顯示選項
        opt1 = ai_response.get("option_1", "Go forward")
        opt2 = ai_response.get("option_2", "Go backward")
        print(f" 1. {opt1}")
        print(f" 2. {opt2}")

        # 玩家輸入
        choice = input("\nChoose your next move (1/2): ").strip()
        
        if choice == '1':
            user_action = f"Player chose option 1: {opt1}. Please advance the story, present a new tech challenge, and provide two new options."
        elif choice == '2':
            user_action = f"Player chose option 2: {opt2}. Please advance the story, present a new tech challenge, and provide two new options."
        else:
            user_action = "Player is idling and entered an invalid command. Sarcastically punish them in the story and re-prompt the same options."

        # 將玩家的抉擇喂回給 AI
        game_history.append({"role": "user", "content": user_action})
        round_count += 1

if __name__ == "__main__":
    main_game()